[book]
title = "The LFE rebar3 Plugin Command Reference"
author = "Duncan McGreggor"
description = "The reference documentation for the LFE rebar3 plugin"
language = "en"

[build]
build-dir = "book/current"

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "lfe-pdp"
preferred-dark-theme = "navy"
additional-css = ["css/custom.css"]
git-repository-url = "https://github.com/lfe-rebar3/rebar3_lfe"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
